### ISSUE TITLE
Change underscore to lodash

### ISSUE THREAD

**Issue by rafanami** [faceleg/flow-interfaces-underscore#1]
Hi Michael, what do you think on using lodash instead of underscore? I came into lodash some years ago, after having a severe performance issue using underscore in node.js.

Cheers

**Comment by faceleg** [comment]
Absolutely agree. I can't swap on the current project though, unfortunately.

Probably worth making another flow-interfaces repo just for lodash, considering the extra functionality they offer compared to _.
